nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://young-coast-00769.herokuapp.com/']
        allow_methods: ['GET']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': 
        allow_origin: ['https://young-coast-00769.herokuapp.com/']
