vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        DISHES:
            uri_prefix: '/public/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
